buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        implementation 'androidx.work:work-runtime-ktx:2.9.0'
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
